version: '1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    volumes:
      - ./data/zookeeper:/logs/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./data/kafka:/logs/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092 # 9092 포트에 카프카 형성
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
